### ISSUE TITLE
Character bug on windows?

### ISSUE THREAD

**Issue by KoleckOLP** [kangalioo/Etternabot#1]
I have praised how nice the dittered characters look in the bars of stats, and I thought you knew about the rest of the bar looks,
but than I loaded your server on a linux PC and seen how much nicer it looks there.
This seems to happen on Windows in chrome and desktop client(also chrome), also firefox on Windows.
Seems to be a charset issue, I'd advise fixing is as it looks ugly and most people run windows.
here is how it looks:
![image](https://user-images.githubusercontent.com/22729896/98906116-da4f1700-24bc-11eb-942d-ac7e4f4a1931.png)

**Comment by kangalio** [comment]
Thank you for the report. I've seen people note this issue a few times, though I thought it's something only some users are experiencing. Good to know this seems to be a universal thing across Windows users.

Unfortunately, there's not really anything I can do here. There's no viable replacement characters for those blocks, so if the system's font rendering messes up with those, best thing I can do is remove the bars entirely.

On the flip side, removing the bars would free enough space in the score card to add information about skillsets improvement since the last call. As in, you could see that your jumpstream rating grew by 0.04, handstream by 0.02 etc. since the last `+profile`

What do you think, should the bars be removed to spare Windows users from the font mis rendering and to make room for a skillsets improvements display?

**Comment by KoleckOLP** [comment]
Yeah, sounds like a reasonable resolution, thank you for quick responce.
Hope to see update soon, have a nice day.

**Comment by KoleckOLP** [comment]
Bump ;)
Just a reminder if you forgot.

**Comment by kangalio** [comment]
Done 26ba94112620d64543091af6b0154dd810d83476
